#make file - this is a comment section

CC=gcc -ansi -pedantic-errors -Wall -Wextra -g -I./../include #compiler
TARGET=fsa #target file name

all:  
	$(CC) fsa.c fsa_test.c -o $(TARGET)

clean:
	rm $(TARGET)

