#make file - this is a comment section

CC=gcc -ansi -pedantic-errors -Wall -Wextra -g -I./../../ds/include #compiler
TARGET=sorted #target file name

all:  
	$(CC)	uid.c test.c -o $(TARGET)

clean:
	rm $(TARGET)

